name: gene_dependency_representations
channels:
  - conda-forge

dependencies:
  - conda-forge::jupyterlab=>3.4.4
  - conda-forge::jupyter
  - conda-forge::ipykernel
  - conda-forge::nb_conda_kernels
  - conda-forge::python=>3.10
  - conda-forge::urllib3=>1.26.9
  - conda-forge::seaborn=>0.11.2
  - conda-forge::plotnine=>0.8.0
  - conda-forge::ipykernel=>6.19.2
  - conda-forge::jupyterlab_code_formatter=>1.5.3
  - conda-forge::isort=>5.12.0 
  - conda-forge::black=>23.1.0 
  - conda-forge::scikit-learn=>1.2.0
  - conda-forge::numpy=>1.23.0
  - conda-forge::pathlib=>1.0.1
  - conda-forge::pandas=>1.5.2
  - conda-forge::matplotlib=>3.6.0
  - conda-forge::keras-tuner=>1.1.3
  - conda-forge::hiplot=>0.1.33
  - pip:
      - blitzgsea==1.3.33


