name: gene_dependency_representations
channels:
  - conda-forge
  - anaconda
dependencies:
  - jupyterlab=>3.4.4
  - python=>3.10
  - urllib3=>1.26.9
  - seaborn=>0.11.2
  - plotnine=>0.8.0
  - ipykernel=>6.19.2
  - scikit-learn=>1.2.0
  - NumPy=>1.23.0
  - pathlib=>1.0.1
  - pandas=>1.5.2
  - matplotlib=>3.6.0
  - keras-tuner=>1.1.3
